export const contestData = [
  {
    id: 1,
    src: "/assets/img/news1.png",
    date: "04 may 2022",
    content: true,
    title: 'Avtooyna" MCHJ korxonasi sizni eng ulug` va aziz bayram...',
    text: '"Avtooyna" MCHJ korxonasi sizni eng ulug` va aziz bayram – O`zbekiston Respublikasi Mustaqilligining 30 yilligi munosabati bilan...',
    toUrl: "/contest-announcement-detail/:1223123",
  },
  {
    id: 2,
    src: "/assets/img/news1.png",
    date: "05 may 2022",
    content: true,
    title: 'Avtooyna" MCHJ korxonasi sizni eng ulug` va aziz bayram...',
    text: '"Avtooyna" MCHJ korxonasi sizni eng ulug` va aziz bayram – O`zbekiston Respublikasi Mustaqilligining 30 yilligi munosabati bilan...',
    toUrl: "/contest-announcement-detail/:1657567123",
  },
  {
    id: 3,
    src: "/assets/img/news1.png",
    date: "06 may 2022",
    content: true,
    title: 'Avtooyna" MCHJ korxonasi sizni eng ulug` va aziz bayram...',
    text: '"Avtooyna" MCHJ korxonasi sizni eng ulug` va aziz bayram – O`zbekiston Respublikasi Mustaqilligining 30 yilligi munosabati bilan...',
    toUrl: "/contest-announcement-detail/:1223123",
  },
  {
    id: 4,
    src: "/assets/img/news1.png",
    date: "07 may 2022",
    content: true,
    title: 'Avtooyna" MCHJ korxonasi sizni eng ulug` va aziz bayram...',
    text: '"Avtooyna" MCHJ korxonasi sizni eng ulug` va aziz bayram – O`zbekiston Respublikasi Mustaqilligining 30 yilligi munosabati bilan...',
    toUrl: "/contest-announcement-detail/:1223123",
  },
  {
    id: 5,
    src: "/assets/img/news1.png",
    date: "07 may 2022",
    content: true,
    title: 'Avtooyna" MCHJ korxonasi sizni eng ulug` va aziz bayram...',
    text: '"Avtooyna" MCHJ korxonasi sizni eng ulug` va aziz bayram – O`zbekiston Respublikasi Mustaqilligining 30 yilligi munosabati bilan...',
    toUrl: "/contest-announcement-detail/:1223123",
  },
  {
    id: 6,
    src: "/assets/img/news1.png",
    date: "07 may 2022",
    content: true,
    title: 'Avtooyna" MCHJ korxonasi sizni eng ulug` va aziz bayram...',
    text: '"Avtooyna" MCHJ korxonasi sizni eng ulug` va aziz bayram – O`zbekiston Respublikasi Mustaqilligining 30 yilligi munosabati bilan...',
    toUrl: "/contest-announcement-detail/:1223123",
  },
];
